import { useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { LoaderCircle, MapPin } from "lucide-react";
import { calculateShipping } from "@/lib/shipping.functions";
import { shippingCartKey, type ShippingOption, type ShippingQuoteItem, type ShippingSelection } from "@/lib/shipping";
import { formatBRL } from "@/lib/format";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Props = { items: ShippingQuoteItem[]; initialZip?: string | undefined; selected?: ShippingSelection | null; onSelect?: (selection: ShippingSelection) => void; onZipChange?: (zip: string) => void };
export function ShippingCalculator({ items, initialZip = "", selected, onSelect, onZipChange }: Props) {
  const calculate = useServerFn(calculateShipping); const [zip, setZip] = useState(initialZip); const [options, setOptions] = useState<ShippingOption[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit() { setLoading(true); setError(null); try { const result = await calculate({ data: { destinationZip: zip, items } }); setZip(result.destinationZip); onZipChange?.(result.destinationZip); setOptions(result.options); const onlyOption = result.options[0]; if (onSelect && result.options.length === 1 && onlyOption) onSelect({ ...onlyOption, destinationZip: result.destinationZip, cartKey: shippingCartKey(items) }); } catch (cause) { setOptions([]); setError(cause instanceof Error ? cause.message : "Não foi possível calcular o frete."); } finally { setLoading(false); } }
  return <div className="mt-5 border-t border-border pt-5"><p className="flex items-center gap-2 text-sm font-semibold"><MapPin className="size-4 text-primary" /> Calcular frete</p><div className="mt-3 flex gap-2"><Input aria-label="CEP de entrega" inputMode="numeric" placeholder="Digite seu CEP" value={zip} maxLength={9} onChange={(event) => { setZip(event.target.value); onZipChange?.(event.target.value); }} required /><Button type="button" variant="outline" disabled={loading || items.length === 0} onClick={() => void submit()}>{loading ? <LoaderCircle className="animate-spin" /> : "Calcular"}</Button></div>{error && <p role="alert" className="mt-2 text-xs text-destructive">{error}</p>}{options.length > 0 && <div className="mt-3 grid gap-2">{options.map((option) => { const active = selected?.id === option.id && selected.destinationZip === zip.replace(/\D/g, ""); const content = <><span><strong>{option.company}</strong> · {option.name}<small className="block text-muted-foreground">Prazo estimado: {option.deliveryDays} {option.deliveryDays === 1 ? "dia útil" : "dias úteis"}</small></span><strong className="text-primary">{option.price === 0 ? "Grátis" : formatBRL(option.price)}</strong></>; return onSelect ? <Button key={option.id} type="button" variant="outline" aria-pressed={active} className={`h-auto w-full justify-between whitespace-normal p-3 text-left ${active ? "border-primary bg-primary/10" : ""}`} onClick={() => onSelect({ ...option, destinationZip: zip.replace(/\D/g, ""), cartKey: shippingCartKey(items) })}>{content}</Button> : <div key={option.id} className="flex items-center justify-between gap-3 rounded-md border border-border bg-background p-3 text-sm">{content}</div>; })}</div>}</div>;
}