/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AcompanharPedidoRouteImport } from './routes/acompanhar-pedido'
import { Route as ComoUsarRouteImport } from './routes/como-usar'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PedidoOrderIdRouteImport } from './routes/pedido.$orderId'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as ApiPublicMelhorEnvioCallbackRouteImport } from './routes/api/public/melhor-envio/callback'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api/public/mercadopago/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanharPedidoRoute = AcompanharPedidoRouteImport.update({
  id: '/acompanhar-pedido',
  path: '/acompanhar-pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoUsarRoute = ComoUsarRouteImport.update({
  id: '/como-usar',
  path: '/como-usar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoOrderIdRoute = PedidoOrderIdRouteImport.update({
  id: '/pedido/$orderId',
  path: '/pedido/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMelhorEnvioCallbackRoute =
  ApiPublicMelhorEnvioCallbackRouteImport.update({
    id: '/api/public/melhor-envio/callback',
    path: '/api/public/melhor-envio/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago/webhook',
    path: '/api/public/mercadopago/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/acompanhar-pedido': typeof AcompanharPedidoRoute
  '/como-usar': typeof ComoUsarRoute
  '/contato': typeof ContatoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/produtos': typeof ProdutosRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/public/melhor-envio/callback': typeof ApiPublicMelhorEnvioCallbackRoute
  '/api/public/mercadopago/webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/acompanhar-pedido': typeof AcompanharPedidoRoute
  '/como-usar': typeof ComoUsarRoute
  '/contato': typeof ContatoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/produtos': typeof ProdutosRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/public/melhor-envio/callback': typeof ApiPublicMelhorEnvioCallbackRoute
  '/api/public/mercadopago/webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/acompanhar-pedido': typeof AcompanharPedidoRoute
  '/como-usar': typeof ComoUsarRoute
  '/contato': typeof ContatoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/produtos': typeof ProdutosRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/public/melhor-envio/callback': typeof ApiPublicMelhorEnvioCallbackRoute
  '/api/public/mercadopago/webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/carrinho'
    | '/checkout'
    | '/acompanhar-pedido'
    | '/como-usar'
    | '/contato'
    | '/privacidade'
    | '/produtos'
    | '/sobre'
    | '/termos'
    | '/pedido/$orderId'
    | '/produto/$slug'
    | '/api/public/melhor-envio/callback'
    | '/api/public/mercadopago/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/carrinho'
    | '/checkout'
    | '/acompanhar-pedido'
    | '/como-usar'
    | '/contato'
    | '/privacidade'
    | '/produtos'
    | '/sobre'
    | '/termos'
    | '/pedido/$orderId'
    | '/produto/$slug'
    | '/api/public/melhor-envio/callback'
    | '/api/public/mercadopago/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/carrinho'
    | '/checkout'
    | '/acompanhar-pedido'
    | '/como-usar'
    | '/contato'
    | '/privacidade'
    | '/produtos'
    | '/sobre'
    | '/termos'
    | '/pedido/$orderId'
    | '/produto/$slug'
    | '/api/public/melhor-envio/callback'
    | '/api/public/mercadopago/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  AcompanharPedidoRoute: typeof AcompanharPedidoRoute
  ComoUsarRoute: typeof ComoUsarRoute
  ContatoRoute: typeof ContatoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProdutosRoute: typeof ProdutosRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  PedidoOrderIdRoute: typeof PedidoOrderIdRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  ApiPublicMelhorEnvioCallbackRoute: typeof ApiPublicMelhorEnvioCallbackRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhar-pedido': {
      id: '/acompanhar-pedido'
      path: '/acompanhar-pedido'
      fullPath: '/acompanhar-pedido'
      preLoaderRoute: typeof AcompanharPedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-usar': {
      id: '/como-usar'
      path: '/como-usar'
      fullPath: '/como-usar'
      preLoaderRoute: typeof ComoUsarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$orderId': {
      id: '/pedido/$orderId'
      path: '/pedido/$orderId'
      fullPath: '/pedido/$orderId'
      preLoaderRoute: typeof PedidoOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/melhor-envio/callback': {
      id: '/api/public/melhor-envio/callback'
      path: '/api/public/melhor-envio/callback'
      fullPath: '/api/public/melhor-envio/callback'
      preLoaderRoute: typeof ApiPublicMelhorEnvioCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago/webhook': {
      id: '/api/public/mercadopago/webhook'
      path: '/api/public/mercadopago/webhook'
      fullPath: '/api/public/mercadopago/webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  AcompanharPedidoRoute: AcompanharPedidoRoute,
  ComoUsarRoute: ComoUsarRoute,
  ContatoRoute: ContatoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProdutosRoute: ProdutosRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  PedidoOrderIdRoute: PedidoOrderIdRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  ApiPublicMelhorEnvioCallbackRoute: ApiPublicMelhorEnvioCallbackRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
